# Generated by Django 4.2.17 on 2025-01-02 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtags', to='events.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Hashtags',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='events.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Categories',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='category_preferences',
            field=models.ManyToManyField(related_name='users', through='users.UserCategory', to='events.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='hashtag_preferences',
            field=models.ManyToManyField(related_name='users', through='users.UserHashtag', to='events.hashtag'),
        ),
    ]
