const events = [
    {
      id: 1,
      title: "Tech Innovators Summit",
      organizer: "Tech World",
      date: "2024-12-15",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Expo Center, City A",
      category: "Technology",
      description: "An event showcasing the latest innovations in technology.",
      image: "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg",
      hashtags: ["#TechSummit", "#Innovation", "#Technology", "#Expo2024"],
    },
    {
      id: 2,
      title: "Music Fiesta",
      organizer: "Live Beats",
      date: "2024-12-20",
      time: "11:00 pm",
      duration: "3 hours",
      venue: "Music Arena, City B",
      category: "Entertainment",
      description: "A night of mesmerizing music performances by top artists.",
      image: "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg",
      hashtags: ["#MusicFiesta", "#LiveMusic", "#Concert", "#Entertainment"],
    },
    {
      id: 3,
      title: "Food Carnival",
      organizer: "Taste Buds",
      date: "2024-12-18",
      time: "12:00 pm",
      duration: "1 hours",
      venue: "Central Park, City C",
      category: "Food",
      description: "Explore delicious cuisines from around the world.",
      image: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg",
      hashtags: ["#FoodCarnival", "#FoodLovers", "#CuisineFest", "#Foodies"],
    },
    {
      id: 4,
      title: "Startup Pitch Fest",
      organizer: "Venture Builders",
      date: "2024-12-22",
      time: "09:00 pm",
      duration: "3 hours",
      venue: "Tech Hub, City D",
      category: "Business",
      description: "Startups pitch their ideas to potential investors and mentors.",
      image: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg",
      hashtags: ["#StartupPitch", "#Entrepreneurship", "#Investors", "#Business"],
    },
    {
      id: 5,
      title: "Art & Craft Expo",
      organizer: "Creative Minds",
      date: "2024-12-25",
      time: "08:00 pm",
      duration: "2 hours",
      venue: "Art Gallery, City E",
      category: "Art",
      description: "An exhibition featuring stunning artworks and crafts.",
      image: "https://images.pexels.com/photos/256540/pexels-photo-256540.jpeg",
      hashtags: ["#ArtExpo", "#Crafts", "#ArtGallery", "#CreativeMinds"],
    },
    {
      id: 6,
      title: "Health & Wellness Seminar",
      organizer: "Wellness Warriors",
      date: "2024-12-12",
      time: "10:00 pm",
      duration: "1 hours",
      venue: "Community Hall, City F",
      category: "Health",
      description: "A seminar focusing on improving mental and physical health.",
      image: "https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg",
      hashtags: ["#HealthSeminar", "#Wellness", "#MentalHealth", "#HealthyLiving"],
    },
    {
      id: 7,
      title: "Charity Run",
      organizer: "Hope Foundation",
      date: "2024-12-10",
      time: "11:00 pm",
      duration: "2 hours",
      venue: "Riverfront, City G",
      category: "Charity",
      description: "Run to raise funds for underprivileged children.",
      image: "https://images.pexels.com/photos/2402777/pexels-photo-2402777.jpeg",
      hashtags: ["#CharityRun", "#Fundraising", "#RunForACause", "#CharityEvent"],
    },
    {
      id: 8,
      title: "Book Fair 2024",
      organizer: "Readers' Guild",
      date: "2024-12-17",
      time: "07:00 pm",
      duration: "3 hours",
      venue: "Library Hall, City H",
      category: "Literature",
      description: "Discover new books and meet your favorite authors.",
      image: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg",
      hashtags: ["#BookFair", "#Reading", "#Literature", "#BookLovers"],
    },
    {
      id: 9,
      title: "Photography Workshop",
      organizer: "Lens Masters",
      date: "2024-12-13",
      time: "04:00 pm",
      duration: "3 hours",
      venue: "Studio Hall, City I",
      category: "Photography",
      description: "Learn professional photography techniques from experts.",
      image: "https://images.pexels.com/photos/274973/pexels-photo-274973.jpeg",
      hashtags: ["#PhotographyWorkshop", "#LensMasters", "#PhotoSkills", "#Photography"],
    },
    {
      id: 10,
      title: "Dance Extravaganza",
      organizer: "Groove Nation",
      date: "2024-12-30",
      time: "15:00 pm",
      duration: "2 hours",
      venue: "Dance Studio, City J",
      category: "Entertainment",
      description: "An exciting showcase of dance performances from various genres.",
      image: "https://images.pexels.com/photos/3586966/pexels-photo-3586966.jpeg",
      hashtags: ["#DanceExtravaganza", "#DanceShow", "#GrooveNation", "#PerformingArts"],
    },
    {
      id: 11,
      title: "AI Revolution Conference",
      organizer: "Tech Forward",
      date: "2025-01-10",
      time: "06:00 pm",
      duration: "1 hours",
      venue: "Innovation Hall, City K",
      category: "Technology",
      description: "Dive into the world of AI and machine learning with industry leaders.",
      image: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg",
      hashtags: ["#AIConference", "#MachineLearning", "#Innovation", "#TechFuture"],
    },
    {
      id: 12,
      title: "Winter Wonderland Festival",
      organizer: "City Events",
      date: "2024-12-25",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Snowy Park, City L",
      category: "Festival",
      description: "Celebrate the magic of winter with fun activities and live performances.",
      image: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg",
      hashtags: ["#WinterFest", "#HolidayFun", "#LiveMusic", "#FamilyEvent"],
    },
    {
      id: 13,
      title: "Yoga and Mindfulness Retreat",
      organizer: "Wellness World",
      date: "2025-02-05",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Peace Resort, City M",
      category: "Health",
      description: "A relaxing retreat focusing on yoga, meditation, and self-care.",
      image: "https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg",
      hashtags: ["#YogaRetreat", "#Mindfulness", "#WellnessJourney", "#HealthyMind"],
    },
    {
      id: 14,
      title: "Coding Bootcamp for Beginners",
      organizer: "Code Academy",
      date: "2025-03-15",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Tech Center, City N",
      category: "Education",
      description: "A hands-on bootcamp to learn coding basics and build your first app.",
      image: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg",
      hashtags: ["#CodingBootcamp", "#LearnToCode", "#Education", "#TechSkills"],
    },
    {
      id: 15,
      title: "Fashion Week 2025",
      organizer: "Style Icon",
      date: "2025-04-10",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Fashion Arena, City O",
      category: "Fashion",
      description: "Experience the latest trends and collections from top designers.",
      image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg",
      hashtags: ["#FashionWeek", "#TrendyStyles", "#DesignerWear", "#RunwayShow"],
    },
    {
      id: 16,
      title: "Robotics Championship",
      organizer: "Robo League",
      date: "2025-05-20",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Robotics Arena, City P",
      category: "Technology",
      description: "A thrilling competition featuring innovative robots from around the globe.",
      image: "https://images.pexels.com/photos/3184450/pexels-photo-3184450.jpeg",
      hashtags: ["#Robotics", "#TechChampionship", "#Innovation", "#FutureTech"],
    },
    {
      id: 17,
      title: "Film Premiere: Galactic Odyssey",
      organizer: "CineWorld",
      date: "2025-06-01",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Cineplex, City Q",
      category: "Entertainment",
      description: "Be the first to watch the highly anticipated sci-fi blockbuster.",
      image: "https://images.pexels.com/photos/276742/pexels-photo-276742.jpeg",
      hashtags: ["#FilmPremiere", "#GalacticOdyssey", "#SciFi", "#MovieNight"],
    },
    {
      id: 19,
      title: "International Book Fair",
      organizer: "Readers' Paradise",
      date: "2025-08-20",
      time: "10:00 pm",
      duration: "2 hours",
      venue: "Grand Library, City S",
      category: "Literature",
      description: "Explore books from around the world and meet renowned authors.",
      image: "https://images.pexels.com/photos/46274/pexels-photo-46274.jpeg",
      hashtags: ["#BookFair", "#InternationalBooks", "#ReadersParadise", "#AuthorMeet"],
    },
  ];
  
  export default events;
  